#!/bin/bash

python run.py --learning_rate 1e-6 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 5e-6 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 1e-5 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 5e-5 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 1e-4 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 5e-4 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 1e-3 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 5e-3 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 1e-2 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 5e-2 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 16
python run.py --learning_rate 1e-6 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 5e-6 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 1e-5 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 5e-5 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 1e-4 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 5e-4 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 1e-3 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 5e-3 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 1e-2 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 5e-2 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 8
python run.py --learning_rate 1e-6 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4
python run.py --learning_rate 5e-6 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4
python run.py --learning_rate 1e-5 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4
python run.py --learning_rate 5e-5 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4
python run.py --learning_rate 1e-4 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4
python run.py --learning_rate 5e-4 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4
python run.py --learning_rate 1e-3 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4
python run.py --learning_rate 5e-3 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4
python run.py --learning_rate 1e-2 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4
python run.py --learning_rate 5e-2 --devices 3 --epoch 20 --patience 5 --batch_size 16 --pre_seq_len 4